### PR TITLE
WIP: Allow coverage submission from Cirrus CI

### PR DESCRIPTION
**Pull request by ararslan**
This will permit coverage submission from builds running on [Cirrus CI](https://cirrus-ci.org), which will fix the coverage step in [my Cirrus template](https://github.com/ararslan/CirrusCI.jl).

Currently a work in progress as I have no idea if this works.

### CODE REVIEW

**Comment by ararslan** [comment]
Interesting issue running the tests on Cirrus:
```
codecovio.jl: Test Failed at /tmp/cirrus-ci-build/test/runtests.jl:212
  Expression: extract_codecov_url((()->begin
            (Coverage.Codecov).submit(fcs; dry_run=true)
        end))
    Expected: ErrorException
  No exception thrown
```

**Comment by fingolfin** [comment]
@ararslan You need to modify the code in runtests.jl around line 143ff, which resets various env vars -- CODECOV_URL, TRAVIS, TRAVIS_BRANCH, ..., APPVEYOR, APPVEYOR_PULL_REQUEST_NUMBER, ...  -- here, the vars for CIRRUS need to be added.

**Comment by ararslan** [comment]
Nice, tests are passing now. Thanks! Looks like I need to adjust something in CirrusCI.jl though.

**Comment by ararslan** [comment]
Oh wait, no I don't, I just need to change how coverage submission is done for this repo on Cirrus.

**Comment by ararslan** [comment]
Alright, so the tests are passing, but it looks like we can't submit to Coveralls from Cirrus without a `COVERALLS_TOKEN` environment variable. We can do that here but it'll be annoying for users to have to get one for their repos...

**Comment by ararslan** [comment]
Looks like FreeBSD Julia 1.0 and 1.1 have the same issue as Linux with MbedTLS...

**Comment by ararslan** [comment]
wat
```
Submitting data to Coveralls...
ERROR: Error while loading expression starting at /tmp/cirrus-ci-build/etc/travis-coverage.jl:3
caused by [exception 1]
HTTP.ExceptionRequest.StatusError(500, HTTP.Messages.Response:
"""
HTTP/1.1 500 Internal Server Error
Date: Sun, 03 Mar 2019 00:12:24 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 59
Connection: keep-alive
Set-Cookie: __cfduid=d0e7c10e350cdf79c65881ccb8d2acc251551571944; expires=Mon, 02-Mar-20 00:12:24 GMT; path=/; domain=.coveralls.io; HttpOnly
Cache-Control: no-cache
Status: 500 Internal Server Error
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger Enterprise 5.3.7
X-Request-Id: 10443d55-5721-4093-9c3d-9a90c3d7e503
X-Runtime: 0.145976
X-XSS-Protection: 1; mode=block
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4b17660c2b3d9ef9-ORD
{"message":"Build processing error.","error":true,"url":""}""")
Stacktrace:
 [1] #request#1 at /root/.julia/packages/HTTP/GN0Te/src/ExceptionRequest.jl:22 [inlined]
 [2] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{Nothing}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::HTTP.Form) at ./none:0
 [3] (::getfield(Base, Symbol("###50#51#53")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::getfield(Base, Symbol("##50#52")){getfield(Base, Symbol("###50#51#53")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)}}, ::Type, ::Vararg{Any,N} where N) at ./error.jl:249
 [4] ##50#52 at ./none:0 [inlined]
 [5] #request#1 at /root/.julia/packages/HTTP/GN0Te/src/RetryRequest.jl:44 [inlined]
 [6] #request at ./none:0 [inlined]
 [7] #request#1(::VersionNumber, ::String, ::Nothing, ::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::HTTP.Form) at /root/.julia/packages/HTTP/GN0Te/src/MessageRequest.jl:47
 [8] request at /root/.julia/packages/HTTP/GN0Te/src/MessageRequest.jl:28 [inlined]
 [9] #request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::HTTP.Form) at /root/.julia/packages/HTTP/GN0Te/src/RedirectRequest.jl:24
 [10] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::HTTP.Form) at /root/.julia/packages/HTTP/GN0Te/src/RedirectRequest.jl:21
 [11] #request#5(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::HTTP.Form) at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:300
 [12] request at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:300 [inlined]
 [13] #request#6 at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:314 [inlined]
 [14] request at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:310 [inlined]
 [15] #post#4(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.post), ::String, ::Array{Pair{SubString{String},SubString{String}},1}, ::HTTP.Form) at /root/.julia/packages/HTTP/GN0Te/src/multipart.jl:132
 [16] #post#3 at /root/.julia/packages/HTTP/GN0Te/src/multipart.jl:131 [inlined]
 [17] post at /root/.julia/packages/HTTP/GN0Te/src/multipart.jl:128 [inlined]
 [18] #submit#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Coverage.Coveralls.submit), ::Array{FileCoverage,1}) at /tmp/cirrus-ci-build/src/coveralls.jl:100
 [19] submit(::Array{FileCoverage,1}) at /tmp/cirrus-ci-build/src/coveralls.jl:59
 [20] top-level scope at /tmp/cirrus-ci-build/etc/travis-coverage.jl:3
 [21] include at ./boot.jl:325 [inlined]
 [22] include_relative(::Module, ::String) at ./loading.jl:1042
 [23] include(::Module, ::String) at ./Base.jl:29
 [24] exec_options(::Base.JLOptions) at ./client.jl:307
 [25] _start() at ./client.jl:476
```

**Comment by ararslan** [comment]
wat redux:
```
Codecov.io API URL:
https://codecov.io/upload/v2?&service=cirrus&branch=aa/cirrus&commit=a147962c27943dd9c149cf999547a7f28900170f&pull_request=192&slug=JuliaCI/Coverage.jl&build=5100440057282560
ERROR: Error while loading expression starting at /tmp/cirrus-ci-build/etc/travis-coverage.jl:8
caused by [exception 1]
HTTP.ExceptionRequest.StatusError(400, HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
Server: nginx/1.13.12
Date: Sun, 03 Mar 2019 00:27:36 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 32989
Connection: keep-alive
X-Xss-Protection: 1; mode=block
Content-Security-Policy: default-src 'self' https://codecov-cdn.storage.googleapis.com;img-src 'self' https://codecov-cdn.storage.googleapis.com/ https://avatar-cdn.atlassian.com https://avatars.io https://bitbucket.org http://www.gravatar.com https://secure.gravatar.com https://avatars0.githubusercontent.com https://assets.gitlab-static.net *.stripe.com data:;frame-src *.stripe.com;connect-src 'self' https://rs.fullstory.com *.stripe.com https://wdzsn5dlywj9.statuspage.io;font-src 'self' https://codecov-cdn.storage.googleapis.com data: https://fonts.gstatic.com;style-src 'self' 'unsafe-inline' https://codecov-cdn.storage.googleapis.com https://fonts.googleapis.com data:;script-src 'self' 'unsafe-eval' https://www.google-analytics.com https://ajax.googleapis.com *.stripe.com https://fullstory.com https://codecov-cdn.storage.googleapis.com 'sha256-CIs2dFHqtIsuMx4Ifc9FncnEWOoKljuLK8jLxvoaSB8=' 'sha256-HXcLlWJ7mifFtqL6lR9wyiD46Nx2DPSLQAKNuS7hyi4=' 'sha256-EY6rgE4jL342XQYDrJU4NwTe01/LA7aEFt5fqciduPs=' 'sha256-Xka1nGXPZvrRUY1sbksxaAL1yz4UM/V/lqPcy2SuKK0=' 'sha256-rw2f6SLqO1pDmvVyWiJscer3uKHUQkjaKZuMY18BtBo=' 'sha256-AlL/9zTip3pSEmOSNSzKmUV82PbVFX3zYfOBCoQHiJo=' 'sha256-4E22mChcLIDnmzkGL+G7FFdbTRJP9QEhaL5HV87ENwM=' 'sha256-4HRm+SsJXTSA0hcixUhh76R+VEivvdioie3szPSQyNY=' 'sha256-m1VD5+xFa7VZ06/K75lEQ5LcwZz8EdEl65GOq5hvdsM=' 'sha256-JdEps8qsUHCFI2A7eawg6dtGvdB71zOZPGBjtJbmoSk=' 'sha256-VFw4sJIt4Zc0+//eYnksN8Ku9qMhbPpHJEkXMWUiD30=' 'sha256-/dTi/ve7ah34TmEka6qw3wGrA9Hhvu+Fixv0xUB8H6s=' 'sha256-uhsd3LKdZUcgVCm7hgZNXuqVqU+gMa/YBa6Ci3aL9uc=' 'sha256-cn8P5aOZvWmX/d2WCXYlruuqA4Ii27w4JjkYaCnpK4w=' 'sha256-mxROEOYdWYUC+DPd1C0Ym7KSkYn7+Pu4R8BIevjDlZI=' 'sha256-zWB9ScoWsUh4WkHIu4UcUF8EP9gcyiZZ1m9UmxOQWNo=' 'sha256-7XV+fBb7hrbjiohc2WHACla7S4FlVDTXQ9Kt67fGvOg=' 'nonce-BERemGb0xJp12ACIGFP3Nd' 'nonce-BDrc12F0xJp12ACIGFP3Nd' 'sha256-NkrmAUONj58QHqeh6TcllquN7F7zAb7G/sC8Cnebdb0=' 'sha256-SNFCiO5ayrLbpolNCNE7w1BfNHQYRCyVwnL4KfvTPmo=' 'sha256-MN7HRw7yJ5t28MuxkXrv1hu1tIHetOGvCgQUpab74kA=';
X-Content-Type-Options: nosniff
Vary: X-PJAX, Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Frame-Option: deny
X-Ua-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="description" content="Code coverage done right. Highly integrated with GitHub, Bitbucket and GitLab.">
<meta name="author" content="@codecov">
<meta name="keywords" content="code, coverage, analysis, testing, development, qa, analyzer">
<link rel="shortcut icon" href="https://codecov-cdn.storage.googleapis.com/4.4.4-6de84ee/media/images/favicon.png">
<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/keefkhehidemnokodkdkejapdgfjmijf">
<meta property="og:url" content="https://codecov.io">
<meta property="og:site_name" content="Codecov">
<meta property="og:title" content="Code coverage done right.">
<meta property="og:description" content="Hosted coverage report highly integrated with GitHub, Bitbucket and GitLab. Awesome pull request comments 
⋮
32989-byte body
""")
Stacktrace:
 [1] #request#1 at /root/.julia/packages/HTTP/GN0Te/src/ExceptionRequest.jl:22 [inlined]
 [2] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{Nothing}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at ./none:0
 [3] (::getfield(Base, Symbol("###50#51#53")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::getfield(Base, Symbol("##50#52")){getfield(Base, Symbol("###50#51#53")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)}}, ::Type, ::Vararg{Any,N} where N) at ./error.jl:249
 [4] ##50#52 at ./none:0 [inlined]
 [5] #request#1 at /root/.julia/packages/HTTP/GN0Te/src/RetryRequest.jl:44 [inlined]
 [6] #request at ./none:0 [inlined]
 [7] #request#1(::VersionNumber, ::String, ::Nothing, ::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /root/.julia/packages/HTTP/GN0Te/src/MessageRequest.jl:47
 [8] request at /root/.julia/packages/HTTP/GN0Te/src/MessageRequest.jl:28 [inlined]
 [9] #request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /root/.julia/packages/HTTP/GN0Te/src/RedirectRequest.jl:24
 [10] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /root/.julia/packages/HTTP/GN0Te/src/RedirectRequest.jl:21
 [11] #request#5(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(HTTP.request), ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:300
 [12] request at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:300 [inlined]
 [13] #request#6 at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:314 [inlined]
 [14] #request at ./none:0 [inlined]
 [15] #post#15 at /root/.julia/packages/HTTP/GN0Te/src/HTTP.jl:396 [inlined]
 [16] #post at ./none:0 [inlined] (repeats 2 times)
 [17] #submit_generic#8(::Base.Iterators.Pairs{Symbol,String,NTuple{6,Symbol},NamedTuple{(:service, :branch, :commit, :pull_request, :slug, :build),NTuple{6,String}}}, ::typeof(Coverage.Codecov.submit_generic), ::Array{FileCoverage,1}) at /tmp/cirrus-ci-build/src/codecovio.jl:226
 [18] (::getfield(Coverage.Codecov, Symbol("#kw##submit_generic")))(::NamedTuple{(:service, :branch, :commit, :pull_request, :slug, :build),NTuple{6,String}}, ::typeof(Coverage.Codecov.submit_generic), ::Array{FileCoverage,1}) at ./none:0
 [19] #submit#2(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Coverage.Codecov.submit), ::Array{FileCoverage,1}) at /tmp/cirrus-ci-build/src/codecovio.jl:137
 [20] submit(::Array{FileCoverage,1}) at /tmp/cirrus-ci-build/src/codecovio.jl:68
 [21] top-level scope at /tmp/cirrus-ci-build/etc/travis-coverage.jl:8
 [22] include at ./boot.jl:325 [inlined]
 [23] include_relative(::Module, ::String) at ./loading.jl:1042
 [24] include(::Module, ::String) at ./Base.jl:29
 [25] exec_options(::Base.JLOptions) at ./client.jl:307
 [26] _start() at ./client.jl:476
```

**Comment by DilumAluthge** [comment]
@ararslan Are you still interested in this PR, or would you like me to close it?

**Comment by ararslan** [comment]
I think it would be useful functionality to have, but I don't have the time (or motivation) to finish it up.

**Comment by DilumAluthge** [comment]
I'm going to close this PR as stale. However, I agree with Alex that this would be useful functionality to have in the future.

**Pull request closed without merging**
