### PR TITLE
Use the newest HTTP to see what happens

### PR DESCRIPTION
**Pull request by ararslan**
Mostly opening this to see what CI says. If there are changes in HTTP that break Coverage then I'll use this PR to fix them.

### CODE REVIEW

**Comment by kshyatt** [comment]
Looking good! 🎉

**Comment by fingolfin** [comment]
What's the status of this? Perhaps rebase it?

**Comment by fingolfin** [comment]
@ararslan ping? This will conflict with #191.

**Comment by ararslan** [comment]
> This will conflict with #191.

I don't see why that would be the case, but at any rate, this PR is not necessary. Pkg will pick up the newest compatible version of HTTP, which has exceeded 0.6.0.

**Comment by fingolfin** [comment]
This PR modifies REQUIRE, the other PR deletes it => conflict (of course one that's trivial to resolve)

**Pull request closed without merging**
