### PR TITLE
Added BoltzmannMachines.jl

### PR DESCRIPTION
**Pull request by stefan-m-lenz**
Hi!
Thanks for your work! I'd like to add a reference to my package.
Best wishes 
Stefan

### CODE REVIEW

**Comment by stefan-m-lenz** [comment]
It seems the problem is that I don't have tests for Julia 0.6 and 0.7 and only test on Julia 1.0?

**Comment by fingolfin** [comment]
If you rebase this, tests should pass.

**Comment by fingolfin** [comment]
@ararslan as in PR #177: couldn't this just be merged as-is, like you did with PR #170?

**Comment by stefan-m-lenz** [comment]
I tried it but I'm really not sure whether this rebase thing I did was correct.

**Comment by fingolfin** [comment]
Indeed, that did not quite work, but should be easy enough to fix: just go into your clone of the repo, and make sure its `master` branch is up to date (so `git checkout master && git pull`). Then switch to your branch and do `git rebase master`. Then use `git push -f` to force-push the rebased branch.

**Comment by stefan-m-lenz** [comment]
Thanks, I did now what you said. It only said "everything up to date". I will probably best delete this pull request and make a new one.

**Pull request closed without merging**
