### PR TITLE
Update Codecov upload API to v4 (replacement for #304)

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #304 

Here is this diff for this PR versus PR #304: https://github.com/JuliaCI/Coverage.jl/compare/aa/codecov-v4...dpa/codecov-v4

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@vtjnash @ararslan Take a look at this PR and let me know what you think.

**Comment by DilumAluthge** [comment]
Also, changing the version of the Codecov API that we use - is that a breaking change or a nonbreaking change?

**Comment by ararslan** [comment]
It's not really exposed to the user in terms of API, so IMO not breaking

**Comment by DilumAluthge** [comment]
> It's not really exposed to the user in terms of API, so IMO not breaking

Sounds good to me!

**Comment by DilumAluthge** [comment]
Alright, let's give this a try.

**Pull request merged**
