### PR TITLE
typo: else instead of elseif

### PR DESCRIPTION
**Pull request by gaika**
Breaks on symbolic links

### CODE REVIEW

**Comment by tkelman** [comment]
how did that work at all? would be good to add a test that hits this branch

**Comment by musm** [comment]
bump @tkelman @ararslan

**Comment by ararslan** [comment]
Still needs a test that hits that branch

**Comment by musm** [comment]
true, @gaika  want to add a test ? (seems  unlikely, since I think this was a regex search of repos incorrectly using else instead of elseif), otherwise it's better to merge this and have the bug fixed without a test rather than keeping than a bug and no test.

**Comment by gaika** [comment]
I don't know how to add a test for it, in my case it only fails when there are emacs backup files (symbolic links to a pipe?) in the directory to cover.

**Comment by ararslan** [comment]
You could try adding a file like that in the directory that's processed as part of the tests.

**Comment by gaika** [comment]
For some reason It doesn't trigger with the test data in the Coverage.jl, here's a stack trace from my test repo:
```
ERROR: SystemError: unable to read directory /home/joe/.julia/v0.6/Test/src/.#
Test.jl: No such file or directory                                           
Stacktrace:
 [1] readdir(::String) at ./file.jl:415
 [2] process_folder(::String) at /home/joe/.julia/v0.6/Coverage/src/Coverage.jl:200                                                                        
 [3] process_folder(::String) at /home/joe/.julia/v0.6/Coverage/src/Coverage.jl:212   
```

Where `.#Test.jl -> joe@test.com.6223:1509759031`

**Comment by ararslan** [comment]
Hm, I'm not really sure what to make of that error.

**Comment by gaika** [comment]
Happens with `Coverage.process_folder(dir)` when there are files still being edited (and locked) in Emacs. The lock file is not a file, so it hits the else clause (instead of elseif) and assumes it is a directory and tries to process it recursively

**Comment by ararslan** [comment]
Okay. Well, what you've change this to is clearly what was intended to be written. We can always figure out an appropriate test for this later, but in the meantime we might as well merge this as-is.

**Pull request merged**
