### PR TITLE
hide token from Codecov.io submission URL logs

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by vtjnash** [comment]
hm. it seems the tests are depending on the token being printed to the log. thoughts?

**Comment by tkelman** [comment]
fix the tests? in what way do they depend on that?

**Comment by vtjnash** [comment]
they assert that we will print the token into the logs (e.g. https://github.com/JuliaCI/Coverage.jl/blob/master/test/runtests.jl#L227) :/

i guess we could print the token if the user passed `dry_run`?

**Comment by tkelman** [comment]
either that, or remove that line

**Comment by tkelman** [comment]
bump

**Comment by fingolfin** [comment]
Would be kinda nice to resurrect this PR

**Comment by fingolfin** [comment]
This was reimplemented in PR #222

**Pull request closed without merging**
