### PR TITLE
Re-enable Coveralls submission from CI

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by vtjnash** [comment]
Probably a coveralls bug. Perhaps if we use the new API, it will bypass their bug (https://github.com/JuliaCI/Coverage.jl/pull/304), otherwise we need to message them for a fix

**Comment by vtjnash** [comment]
Oh, perhaps it is one of these issues: https://github.com/lemurheavy/coveralls-public/issues/1527

**Comment by DilumAluthge** [comment]
Isn't #304 for Codecov, not Coveralls?

**Comment by DilumAluthge** [comment]
> Oh, perhaps it is one of these issues: [lemurheavy/coveralls-public#1527](https://github.com/lemurheavy/coveralls-public/issues/1527)

Why does Coveralls want us to send them the `GITHUB_TOKEN` for our repo? It would be fine if they want us to send a Coveralls-specific token that is e.g. generated on their website. But the `GITHUB_TOKEN` has write access to our repo.... I don't really want to send that token to them just to upload a coverage report.

For Codecov, you just send a Codecov-specific token that is generated on the Codecov website.

**Comment by DilumAluthge** [comment]
> > Oh, perhaps it is one of these issues: [lemurheavy/coveralls-public#1527](https://github.com/lemurheavy/coveralls-public/issues/1527)
> 
> Why does Coveralls want us to send them the `GITHUB_TOKEN` for our repo? It would be fine if they want us to send a Coveralls-specific token that is e.g. generated on their website. But the `GITHUB_TOKEN` has write access to our repo.... I don't really want to send that token to them just to upload a coverage report.
> 
> For Codecov, you just send a Codecov-specific token that is generated on the Codecov website.

https://github.com/coverallsapp/github-action/issues/68

**Pull request closed without merging**
